# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

# Set use_modular_headers globally
use_modular_headers!

target 'ReactNativeProject' do
  # Add your existing pods here if you have any...


  # Add YogaKit pod
  pod 'YogaKit', '~> 1.18.1'

  # Resolve react_native_pods.rb with node to allow for hoisting
  require File.join(__dir__, '..', 'node_modules', 'react-native', 'scripts', 'react_native_pods')

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{config[:appPath]}"
  )

  target 'ReactNativeProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # React Native post install steps
    react_native_post_install(installer)

    # Add any custom post-installation steps here if needed...
  end
end