require 'json'
require 'open3'

def react_native_pods_script_path
  node_script = <<-SCRIPT
    const path = require('path');
    const scriptPath = require.resolve('react-native/scripts/react_native_pods.rb', { paths: [process.argv[1]] });
    console.log(scriptPath);
  SCRIPT
  command = ['node', '-e', node_script, __FILE__]
  path, status = Open3.capture2(*command)
  path.strip if status.success?
end

resolved_script_path = react_native_pods_script_path

platform :ios, '10.0'

target 'ReactNativeProject' do
  # Add any other dependencies you need

  pod 'RCT-Folly', :path => resolved_script_path

  # Use Flipper if it's not explicitly disabled
  flipper_enabled = ENV['NO_FLIPPER'] != '1'
  if flipper_enabled
    flipper_configuration = 'Flipper'
    pod flipper_configuration, :path => resolved_script_path + "/Flipper"
    pod 'DoubleConversion', :podspec => "#{resolved_script_path}/DoubleConversion.podspec"
    pod 'Flipper-Folly', :podspec => "#{resolved_script_path}/Flipper-Folly.podspec"
    pod 'Flipper-Glog', :podspec => "#{resolved_script_path}/Flipper-Glog.podspec"
    pod 'Flipper-PeerTalk', :podspec => "#{resolved_script_path}/Flipper-PeerTalk.podspec"
    pod 'Flipper-RSocket', :podspec => "#{resolved_script_path}/Flipper-RSocket.podspec"
  end

  # Add other pods as needed
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'Flipper'
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
  end

  react_native_post_install(
    installer,
    resolved_script_path,
    :mac_catalyst_enabled => false
  )
end
